name: NodeJS with Webpack

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

#     - name: Build
#       run: |
#         npm install
#         npm run build
        
    # Deploy
    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.2.11
      env:
        SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
        ARGS: "-avz --delete"
        SOURCE: ""
        REMOTE_HOST: ${{ secrets.HOST }}
        REMOTE_USER: root
        TARGET: "/root/code/nest-api-action"
        
    # reload
    - name: ls -a via ssh
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: cd /root/code/nest-api-action && npm i && pm2 reload 0
        host: ${{ secrets.HOST }}
        username: root
        privateKey: ${{ secrets.ACCESS_TOKEN}}
